import { readFile, mkdir, writeFile } from 'node:fs/promises';
import { createHash } from 'node:crypto';
const files=['validation','service-config','recipient-directory','service','webhooks','events','connection-ui','recipient-ui','protocol','worker'];
const assets={};
for (const [path,file,type] of [['/','web/index.html','text/html; charset=utf-8'],['/board.js','web/board.js','text/javascript; charset=utf-8'],['/state.js','web/state.js','text/javascript; charset=utf-8'],['/board.css','web/board.css','text/css; charset=utf-8'],['/recipient-picker.js','web/recipient-picker.js','text/javascript; charset=utf-8'],['/recipient-picker.css','web/recipient-picker.css','text/css; charset=utf-8']])
  assets[path]={body:await readFile(file,'utf8'),type};
const sources=await Promise.all(files.map(f=>readFile(`src/${f}.mjs`,'utf8')));
const skillText=await readFile('skills/paprika-messenger/SKILL.md','utf8');
const frontmatter=Object.fromEntries(skillText.split('---')[1].trim().split('\n').map(line=>{const colon=line.indexOf(':');return [line.slice(0,colon).trim(),line.slice(colon+1).trim()];}));
const skillResources={};
for (const file of ['SKILL.md','agents/openai.yaml','assets/dot-icon.png','references/connect.md','references/connection-ui.md','references/recipient-picker.md','references/direct.md','references/notifications.md','scripts/parse-cadence.mjs','scripts/get-thread-id.mjs','scripts/prepare-notification.mjs','scripts/prepare-delivery.mjs','scripts/notification-state.mjs']) {
  const uri=`skill://dot-agent-board/paprika-messenger/${file}`;
  const bytes=await readFile(`skills/paprika-messenger/${file}`);
  skillResources[uri]=file.endsWith('.png')
    ? {uri,mimeType:'image/png',blob:bytes.toString('base64')}
    : {uri,mimeType:file.endsWith('.md')?'text/markdown':file.endsWith('.mjs')?'text/javascript':'application/yaml',text:bytes.toString('utf8')};
}
const skillEntries=[{uri:'skill://dot-agent-board/paprika-messenger/SKILL.md',frontmatter,resources:Object.values(skillResources).map(r=>({uri:r.uri,digest:`sha256:${createHash('sha256').update(r.blob?Buffer.from(r.blob,'base64'):r.text,'utf8').digest('hex')}`}))}];
const uiResources={'ui://paprika-messenger/connection/v1.html':{
  uri:'ui://paprika-messenger/connection/v1.html',mimeType:'text/html;profile=mcp-app',
  text:await readFile('web/connection-controls.html','utf8'),
  _meta:{ui:{prefersBorder:true,csp:{connectDomains:[],resourceDomains:[]}},
    'openai/widgetDescription':'Incoming-message controls for this chat: explicitly enable receiving, optionally record receipts after reading, check status or stop this chat’s verified binding.'}
}};
const recipientScript=(await Promise.all(['web/recipient-picker.js','web/recipient-host.js'].map(file=>readFile(file,'utf8'))))
  .map(source=>source.replace(/^import .*?;\r?\n/gm,'').replace(/^export /gm,'')).join('\n');
uiResources['ui://paprika-messenger/recipients/v1.html']={uri:'ui://paprika-messenger/recipients/v1.html',mimeType:'text/html;profile=mcp-app',
  text:(await readFile('web/recipient-controls.html','utf8')).replace('/* RECIPIENT_CSS */',()=>assets['/recipient-picker.css'].body).replace('/* RECIPIENT_SCRIPT */',()=>recipientScript),
  _meta:{ui:{prefersBorder:true,csp:{connectDomains:[],resourceDomains:[]}},'openai/ui':{availableDisplayModes:['inline'],preferredDisplayMode:'inline'},
    'openai/widgetDescription':'Search registered conversations by title or ID, grouped by native project, with a board filter defaulting to main. Choose a recipient for the next message or send previously agreed content after explicit selection.'}};
await mkdir('dist',{recursive:true});
await writeFile('dist/_worker.js',`// Generated by scripts/build.mjs. Source: src/, web/, skills/.\nconst assets=${JSON.stringify(assets)};\nconst skillEntries=${JSON.stringify(skillEntries)};\nconst skillResources=${JSON.stringify(skillResources)};\nconst uiResources=${JSON.stringify(uiResources)};\n`+sources.map(s=>s.replace(/^import .*? from '\.\/.*?';\r?\n/gm,'')).join('\n'));
await mkdir('dist/server',{recursive:true});
await writeFile('dist/server/index.js',await readFile('dist/_worker.js'));
console.log('Built dist/_worker.js (self-contained Cloudflare Worker).');
